(()=>{
"use strict";
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const K={client:"tri.client",base:"tri.base",token:"tri.token",host:"tri.host",demoAlbums:"tri.demoAlbums"};
const S={mode:"setup",client:localStorage.getItem(K.client)||"",base:localStorage.getItem(K.base)||"/Photos",token:localStorage.getItem(K.token)||"",host:localStorage.getItem(K.host)||"",path:"",stack:[],selected:new Map(),albums:[],album:null,viewerItems:[],viewerIndex:0};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const media=m=>!m.isfolder&&(((m.contenttype||"").startsWith("image/"))||((m.contenttype||"").startsWith("video/"))||/\.(jpe?g|png|heic|webp|gif|mp4|mov|m4v|avi|3gp)$/i.test(m.name||""));
const svgThumb=(label,hue=180)=>`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="800"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="hsl(${hue} 70% 70%)"/><stop offset="1" stop-color="hsl(${(hue+45)%360} 60% 35%)"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/><circle cx="650" cy="150" r="70" fill="rgba(255,255,255,.8)"/><path d="M0 620L210 390l130 150 120-120 340 300H0z" fill="rgba(255,255,255,.72)"/><rect x="35" y="35" rx="18" width="390" height="70" fill="rgba(0,0,0,.35)"/><text x="60" y="83" font-family="Arial" font-size="34" fill="white">${label}</text></svg>`)}`;
function demoData(){let id=1;const file=(name,label,hue,type="image/jpeg")=>({fileid:`d${id++}`,name,contenttype:type,thumb:svgThumb(label,hue),created:"2026-01-01"});const folder=(name,path,contents)=>({isfolder:true,name,path,contents});return folder("Photos","/Photos",[
 folder("2026","/Photos/2026",[
  folder("2026-07","/Photos/2026/2026-07",[
   folder("2026-07-14","/Photos/2026/2026-07/2026-07-14",[
    file("20260714_091245.jpg","Petit-déjeuner",28),file("20260714_101522.jpg","Plage",192),file("20260714_103104.jpg","Baignade",207),file("20260714_120015.jpg","Famille",330),file("20260714_164530.jpg","Cocotiers",115),file("20260714_180412.mp4","Vidéo plage",205,"video/mp4")
   ]),
   folder("2026-07-15","/Photos/2026/2026-07/2026-07-15",[
    file("20260715_084402.jpg","Terrasse",32),file("20260715_101159.jpg","Mer",195),file("20260715_132010.jpg","Balade",100),file("20260715_171804.jpg","Coucher soleil",18)
   ])
  ]),
  folder("2026-08","/Photos/2026/2026-08",[
   folder("2026-08-03","/Photos/2026/2026-08/2026-08-03",[
    file("20260803_100022.jpg","Anniversaire",300),file("20260803_110701.jpg","Gâteau",345),file("20260803_120233.jpg","Famille",260)
   ])
  ])
 ]),
 folder("2025","/Photos/2025",[
  folder("2025-12","/Photos/2025/2025-12",[
   folder("2025-12-25","/Photos/2025/2025-12/2025-12-25",[
    file("20251225_090010.jpg","Noël",350),file("20251225_120045.jpg","Repas",25),file("20251225_160030.jpg","Famille",320)
   ])
  ])
 ])
]);}
const DEMO_ROOT=demoData();
function demoFind(path,node=DEMO_ROOT){if(node.path===path)return node;for(const c of node.contents||[])if(c.isfolder){const f=demoFind(path,c);if(f)return f}return null}
function toast(t,ms=3000){const e=$("#toast");e.textContent=t;e.classList.remove("hidden");clearTimeout(toast.x);toast.x=setTimeout(()=>e.classList.add("hidden"),ms)}
function busy(v){$("#busy").classList.toggle("hidden",!v)}
function screen(n){$("#screenSetup").classList.toggle("hidden",n!=="setup");$("#screenMain").classList.toggle("hidden",n!=="main");$("#btnSettings").classList.toggle("hidden",n!=="main");$("#btnLogout").classList.toggle("hidden",n!=="main")}
function setMode(mode){S.mode=mode;const demo=mode==="demo";$("#modeBadge").classList.toggle("hidden",!demo);$("#demoNotice").classList.toggle("hidden",!demo);$("#subtitle").textContent=demo?"mode démonstration • aucune donnée pCloud":"pCloud • albums virtuels";$("#albumSubtitle").textContent=demo?"Albums de démonstration stockés localement":"Collections pCloud — aucune copie des originaux";$("#shareHint").textContent=demo?"Le lien ci-dessous sera simulé pour tester l'ergonomie.":"Le lien sera créé par pCloud."}
async function api(method,params={}){if(!S.host||!S.token)throw new Error("Session pCloud absente");const q=new URLSearchParams(params);const r=await fetch(`https://${S.host}/${method}?${q}`,{headers:{Authorization:`Bearer ${S.token}`},cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(Number(d.result||0)!==0){const e=new Error(d.error||`Erreur pCloud ${d.result}`);e.code=d.result;throw e}return d}
function redirectUri(){return location.href.split("#")[0].split("?")[0]}
function oauth(){const c=$("#clientIdInput").value.trim();let b=$("#basePathInput").value.trim()||"/Photos";if(!b.startsWith("/"))b="/"+b;if(!c)return toast("Saisis le Client ID pCloud.");S.client=c;S.base=b;localStorage.setItem(K.client,c);localStorage.setItem(K.base,b);const st=crypto.getRandomValues(new Uint32Array(4)).join("-");sessionStorage.setItem("tri.state",st);const u=new URL("https://my.pcloud.com/oauth2/authorize");u.searchParams.set("client_id",c);u.searchParams.set("response_type","token");u.searchParams.set("redirect_uri",redirectUri());u.searchParams.set("state",st);u.searchParams.set("permissions","manageshares");location.assign(u.toString())}
function consume(){if(!location.hash.includes("access_token="))return;const p=new URLSearchParams(location.hash.slice(1)),tok=p.get("access_token"),host=p.get("hostname"),st=p.get("state"),expected=sessionStorage.getItem("tri.state");if(!tok||!host)return toast("Réponse OAuth incomplète.");if(expected&&st!==expected)return toast("Échec du contrôle de sécurité OAuth.",5000);S.token=tok;S.host=host;localStorage.setItem(K.token,tok);localStorage.setItem(K.host,host);sessionStorage.removeItem("tri.state");history.replaceState(null,"",redirectUri())}
async function valid(){if(!S.token||!S.host)return false;try{await api("userinfo");return true}catch{return false}}
function quit(){if(S.mode==="real"){localStorage.removeItem(K.token);localStorage.removeItem(K.host);S.token="";S.host=""}S.selected.clear();S.stack=[];setMode("setup");screen("setup");toast("Session fermée.")}
async function folder(path,push=true){busy(true);try{let items=[],resolved=path;if(S.mode==="demo"){const f=demoFind(path)||DEMO_ROOT;items=f.contents||[];resolved=f.path}else{const d=await api("listfolder",{path,recursive:0});items=d.metadata.contents||[];resolved=d.metadata.path||path}if(push&&S.path&&S.path!==resolved)S.stack.push(S.path);S.path=resolved;$("#currentPath").textContent=S.path;renderFolder(items)}catch(e){toast(`Dossier : ${e.message}`,5000)}finally{busy(false)}}
function renderFolder(items){const g=$("#photoGrid");g.innerHTML="";const fs=items.filter(x=>x.isfolder).sort((a,b)=>a.name.localeCompare(b.name,"fr"));const ms=items.filter(media).sort((a,b)=>(b.created||"").localeCompare(a.created||""));$("#photosEmpty").classList.toggle("hidden",fs.length+ms.length>0);for(const f of fs){const e=document.createElement("button");e.className="tile folder";e.innerHTML=`<div class="folder-icon">📁</div><div class="folder-name">${esc(f.name)}</div><div class="folder-hint">Ouvrir</div>`;e.onclick=()=>folder(f.path||`${S.path}/${f.name}`);g.appendChild(e)}for(const m of ms){const e=document.createElement("div");e.className="tile";e.dataset.fileid=String(m.fileid);e.innerHTML=`<div class="thumb-wrap"><div class="check">✓</div><img data-thumb-fileid="${m.fileid}" alt="${esc(m.name)}" loading="lazy">${(m.contenttype||"").startsWith("video/")?'<div class="video-badge">▶ vidéo</div>':""}</div><div class="tile-info" title="${esc(m.name)}">${esc(m.name)}</div>`;e.querySelector(".check").onclick=ev=>{ev.stopPropagation();select(m,e)};e.querySelector(".thumb-wrap").onclick=()=>viewer(m,ms);g.appendChild(e)}if(S.mode==="demo")for(const m of ms){const img=g.querySelector(`img[data-thumb-fileid="${m.fileid}"]`);if(img)img.src=m.thumb}else thumbs(ms,g);syncSel()}
async function thumbs(items,root=document,size="400x400"){const ids=items.map(x=>x.fileid).filter(Boolean);for(let i=0;i<ids.length;i+=80){try{const d=await api("getthumbslinks",{fileids:ids.slice(i,i+80).join(","),size,crop:1});for(const t of d.thumbs||[]){if(Number(t.result)!==0||!t.hosts?.length||!t.path)continue;const img=root.querySelector(`img[data-thumb-fileid="${String(t.fileid)}"]`);if(img)img.src=`https://${t.hosts[0]}${t.path}`}}catch(e){console.warn(e)}}}
function select(m,e){const id=String(m.fileid);if(S.selected.has(id)){S.selected.delete(id);e.classList.remove("selected")}else{S.selected.set(id,m);e.classList.add("selected")}syncSel()}
function syncSel(){const n=S.selected.size;$("#selectionCount").textContent=n;$("#selectionBar").classList.toggle("hidden",n===0);$$('.tile[data-fileid]').forEach(e=>e.classList.toggle("selected",S.selected.has(e.dataset.fileid)))}
function clearSel(){S.selected.clear();syncSel()}
function getDemoAlbums(){try{return JSON.parse(localStorage.getItem(K.demoAlbums)||"[]")}catch{return []}}
function saveDemoAlbums(a){localStorage.setItem(K.demoAlbums,JSON.stringify(a))}
async function createAlbum(name){const files=[...S.selected.values()];if(!files.length)throw new Error("Aucune sélection");if(S.mode==="demo"){const a=getDemoAlbums();const item={id:`demo-${Date.now()}`,name,items:files.map(x=>({...x})),created:new Date().toISOString()};a.push(item);saveDemoAlbums(a);return item}const d=await api("collection_create",{name,type:0,fileids:files.map(x=>x.fileid).join(",")});return Array.isArray(d.collection)?d.collection[0]:d.collection}
async function addAlbum(id){const files=[...S.selected.values()];if(!files.length)throw new Error("Aucune sélection");if(S.mode==="demo"){const a=getDemoAlbums(),target=a.find(x=>x.id===id);if(!target)throw new Error("Album introuvable");const have=new Set(target.items.map(x=>String(x.fileid)));for(const f of files)if(!have.has(String(f.fileid)))target.items.push({...f});saveDemoAlbums(a);return target}return api("collection_linkfiles",{collectionid:id,fileids:files.map(x=>x.fileid).join(",")})}
async function albums(){busy(true);try{if(S.mode==="demo")S.albums=getDemoAlbums().map(a=>({id:a.id,name:a.name,items:a.items.length}));else{const d=await api("collection_list",{showfiles:1,pagesize:4});S.albums=(d.collections||[]).filter(a=>!a.system)}renderAlbums()}catch(e){toast(`Albums : ${e.message}`,5000)}finally{busy(false)}}
function renderAlbums(){const g=$("#albumGrid");g.innerHTML="";$("#albumsEmpty").classList.toggle("hidden",S.albums.length>0);for(const a of S.albums){const e=document.createElement("div");e.className="album-card";e.innerHTML=`<div class="album-cover">📚</div><div class="album-title">${esc(a.name)}</div><div class="album-count">${Number(a.items||0)} élément(s)</div><button class="secondary wide">Ouvrir</button>`;e.querySelector("button").onclick=()=>openAlbum(a.id);g.appendChild(e)}}
async function openAlbum(id){busy(true);try{let album,items;if(S.mode==="demo"){album=getDemoAlbums().find(x=>x.id===id);if(!album)throw new Error("Album introuvable");items=album.items}else{const d=await api("collection_details",{collectionid:id});album=d.collection;items=(album.contents||[]).filter(media)}S.album=album;$("#albumViewTitle").textContent=album.name||"Album";$("#albumViewMeta").textContent=`${items.length} élément(s)`;const g=$("#albumViewGrid");g.innerHTML="";for(const m of items){const e=document.createElement("div");e.className="tile";e.innerHTML=`<div class="thumb-wrap"><img data-thumb-fileid="${m.fileid}" alt="${esc(m.name)}" loading="lazy">${(m.contenttype||"").startsWith("video/")?'<div class="video-badge">▶ vidéo</div>':""}</div><div class="tile-info">${esc(m.name)}</div>`;e.querySelector(".thumb-wrap").onclick=()=>viewer(m,items);g.appendChild(e)}$("#albumViewDialog").showModal();if(S.mode==="demo")for(const m of items){const img=g.querySelector(`img[data-thumb-fileid="${m.fileid}"]`);if(img)img.src=m.thumb}else await thumbs(items,g)}catch(e){toast(`Album : ${e.message}`,5000)}finally{busy(false)}}
async function viewer(m,items=[m]){S.viewerItems=items;S.viewerIndex=Math.max(0,items.findIndex(x=>String(x.fileid)===String(m.fileid)));$("#viewerDialog").showModal();await renderViewer()}
async function renderViewer(){const m=S.viewerItems[S.viewerIndex];if(!m)return;$("#viewerCaption").textContent=`${m.name||""} • ${S.viewerIndex+1}/${S.viewerItems.length}`;const box=$("#viewerMedia");box.innerHTML="";if((m.contenttype||"").startsWith("video/")&&S.mode==="demo"){box.innerHTML=`<div class="video-demo"><div class="play-circle">▶</div><strong>${esc(m.name)}</strong><span>Lecture vidéo simulée en mode démo</span></div>`;return}const img=document.createElement("img");img.alt=m.name||"";box.appendChild(img);if(S.mode==="demo"){img.src=m.thumb;return}try{const x=await api("getthumbslinks",{fileids:m.fileid,size:"2048x1024",crop:0});const t=x.thumbs?.[0];if(!t||Number(t.result)!==0||!t.hosts?.length)throw new Error(t?.error||"Aperçu indisponible");img.src=`https://${t.hosts[0]}${t.path}`}catch(e){$("#viewerCaption").textContent=`${m.name||""} — ${e.message}`}}
function moveViewer(delta){if(!S.viewerItems.length)return;S.viewerIndex=(S.viewerIndex+delta+S.viewerItems.length)%S.viewerItems.length;renderViewer()}
async function share(pwd){if(!S.album?.id)throw new Error("Aucun album ouvert");if(S.mode==="demo")return `${location.origin}${location.pathname}?demo-share=${encodeURIComponent(S.album.id)}${pwd?"&protected=1":""}`;const p=await api("getcollectionpublink",{collectionid:S.album.id});if(!p.linkid||!p.link)throw new Error("Lien non créé");if(pwd){try{await api("changepublink",{linkid:p.linkid,linkpassword:pwd})}catch(e){try{await api("deletepublink",{linkid:p.linkid})}catch{}throw new Error("Mot de passe non appliqué : lien supprimé par sécurité")}}return p.link}
function view(v){$$('.tab').forEach(t=>t.classList.toggle("active",t.dataset.view===v));$("#viewPhotos").classList.toggle("hidden",v!=="photos");$("#viewAlbums").classList.toggle("hidden",v!=="albums");if(v==="albums")albums()}
async function startDemo(){setMode("demo");S.path="";S.stack=[];S.selected.clear();screen("main");view("photos");await folder("/Photos",false);toast("Mode démonstration activé.")}
async function boot(){consume();$("#clientIdInput").value=S.client;$("#basePathInput").value=S.base;$("#btnDemo").onclick=startDemo;$("#btnSaveAndLogin").onclick=oauth;$("#btnLogout").onclick=quit;$("#btnSettings").onclick=()=>{screen("setup");$("#clientIdInput").value=S.client;$("#basePathInput").value=S.base};$("#btnRefresh").onclick=()=>folder(S.path||S.base,false);$("#btnUp").onclick=()=>{const p=S.stack.pop();if(p)folder(p,false);else if(S.path!==S.base)folder(S.mode==="demo"?"/Photos":S.base,false)};$("#btnClearSelection").onclick=clearSel;$$('.tab').forEach(t=>t.onclick=()=>view(t.dataset.view));$("#btnRefreshAlbums").onclick=albums;$("#btnCreateAlbum").onclick=()=>{$("#albumNameInput").value="";$("#albumDialog").showModal();setTimeout(()=>$("#albumNameInput").focus(),80)};$("#btnConfirmCreateAlbum").onclick=async ev=>{ev.preventDefault();const n=$("#albumNameInput").value.trim();if(!n)return toast("Donne un nom à l'album.");busy(true);try{await createAlbum(n);$("#albumDialog").close();clearSel();toast(`Album « ${n} » créé.`)}catch(e){toast(e.message,5000)}finally{busy(false)}};$("#btnAddExisting").onclick=async()=>{await albums();const s=$("#albumSelect");s.innerHTML="";for(const a of S.albums){const o=document.createElement("option");o.value=a.id;o.textContent=`${a.name} (${a.items||0})`;s.appendChild(o)}if(!S.albums.length)return toast("Crée d'abord un album.");$("#addDialog").showModal()};$("#btnConfirmAdd").onclick=async ev=>{ev.preventDefault();const id=$("#albumSelect").value;if(!id)return;busy(true);try{await addAlbum(id);$("#addDialog").close();clearSel();toast("Ajouté à l'album.")}catch(e){toast(e.message,5000)}finally{busy(false)}};$("#btnCloseAlbumView").onclick=()=>$("#albumViewDialog").close();$("#viewerClose").onclick=()=>$("#viewerDialog").close();$("#viewerPrev").onclick=()=>moveViewer(-1);$("#viewerNext").onclick=()=>moveViewer(1);document.addEventListener("keydown",e=>{if(!$("#viewerDialog").open)return;if(e.key==="ArrowLeft")moveViewer(-1);if(e.key==="ArrowRight")moveViewer(1);if(e.key==="Escape")$("#viewerDialog").close()});$("#btnShareAlbum").onclick=()=>{$("#sharePasswordInput").value="";$("#shareExpiry").value="";$("#shareResult").classList.add("hidden");$("#shareDialog").showModal()};$("#btnConfirmShare").onclick=async ev=>{ev.preventDefault();busy(true);try{const l=await share($("#sharePasswordInput").value.trim());$("#shareLinkOutput").value=l;$("#shareResult").classList.remove("hidden");toast(S.mode==="demo"?"Lien simulé créé.":"Lien pCloud créé.")}catch(e){toast(e.message,6000)}finally{busy(false)}};$("#btnCopyShare").onclick=async()=>{const v=$("#shareLinkOutput").value;try{await navigator.clipboard.writeText(v)}catch{$("#shareLinkOutput").select();document.execCommand("copy")}toast("Lien copié.")};if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(console.warn);if(await valid()){setMode("real");screen("main");folder(S.base,false)}else{setMode("setup");screen("setup")}}
boot().catch(e=>toast(`Démarrage : ${e.message}`,6000));
})();