(()=>{
"use strict";
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const K={client:"tri.client",base:"tri.base",token:"tri.token",host:"tri.host"};
const S={client:localStorage.getItem(K.client)||"",base:localStorage.getItem(K.base)||"/Photos",token:localStorage.getItem(K.token)||"",host:localStorage.getItem(K.host)||"",path:"",stack:[],selected:new Map(),albums:[],album:null};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const media=m=>!m.isfolder&&(((m.contenttype||"").startsWith("image/"))||((m.contenttype||"").startsWith("video/"))||/\.(jpe?g|png|heic|webp|gif|mp4|mov|m4v|avi|3gp)$/i.test(m.name||""));
function toast(t,ms=3000){const e=$("#toast");e.textContent=t;e.classList.remove("hidden");clearTimeout(toast.x);toast.x=setTimeout(()=>e.classList.add("hidden"),ms)}
function busy(v){$("#busy").classList.toggle("hidden",!v)}
function screen(n){$("#screenSetup").classList.toggle("hidden",n!=="setup");$("#screenMain").classList.toggle("hidden",n!=="main");$("#btnLogout").classList.toggle("hidden",n!=="main")}
async function api(method,params={}){if(!S.host||!S.token)throw new Error("Session pCloud absente");const q=new URLSearchParams(params);const r=await fetch(`https://${S.host}/${method}?${q}`,{headers:{Authorization:`Bearer ${S.token}`},cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(Number(d.result||0)!==0){const e=new Error(d.error||`Erreur pCloud ${d.result}`);e.code=d.result;throw e}return d}
function redirectUri(){return location.href.split("#")[0].split("?")[0]}
function oauth(){const c=$("#clientIdInput").value.trim();let b=$("#basePathInput").value.trim()||"/Photos";if(!b.startsWith("/"))b="/"+b;if(!c)return toast("Saisis le Client ID pCloud.");S.client=c;S.base=b;localStorage.setItem(K.client,c);localStorage.setItem(K.base,b);const st=crypto.getRandomValues(new Uint32Array(4)).join("-");sessionStorage.setItem("tri.state",st);const u=new URL("https://my.pcloud.com/oauth2/authorize");u.searchParams.set("client_id",c);u.searchParams.set("response_type","token");u.searchParams.set("redirect_uri",redirectUri());u.searchParams.set("state",st);u.searchParams.set("permissions","manageshares");location.assign(u.toString())}
function consume(){if(!location.hash.includes("access_token="))return;const p=new URLSearchParams(location.hash.slice(1)),tok=p.get("access_token"),host=p.get("hostname"),st=p.get("state"),expected=sessionStorage.getItem("tri.state");if(!tok||!host)return toast("Réponse OAuth incomplète.");if(expected&&st!==expected)return toast("Échec du contrôle de sécurité OAuth.",5000);S.token=tok;S.host=host;localStorage.setItem(K.token,tok);localStorage.setItem(K.host,host);sessionStorage.removeItem("tri.state");history.replaceState(null,"",redirectUri())}
async function valid(){if(!S.token||!S.host)return false;try{await api("userinfo");return true}catch{return false}}
function logout(){localStorage.removeItem(K.token);localStorage.removeItem(K.host);S.token="";S.host="";S.selected.clear();screen("setup");toast("Déconnecté de cette application.")}
async function folder(path,push=true){busy(true);try{const d=await api("listfolder",{path,recursive:0});if(push&&S.path&&S.path!==path)S.stack.push(S.path);S.path=d.metadata.path||path;$("#currentPath").textContent=S.path;renderFolder(d.metadata.contents||[])}catch(e){toast(`Dossier : ${e.message}`,5000)}finally{busy(false)}}
function renderFolder(items){const g=$("#photoGrid");g.innerHTML="";const fs=items.filter(x=>x.isfolder).sort((a,b)=>a.name.localeCompare(b.name,"fr"));const ms=items.filter(media).sort((a,b)=>(b.created||"").localeCompare(a.created||""));$("#photosEmpty").classList.toggle("hidden",fs.length+ms.length>0);for(const f of fs){const e=document.createElement("button");e.className="tile folder";e.innerHTML=`<div class="folder-icon">📁</div><div class="folder-name">${esc(f.name)}</div>`;e.onclick=()=>folder(f.path||`${S.path}/${f.name}`);g.appendChild(e)}for(const m of ms){const e=document.createElement("div");e.className="tile";e.dataset.fileid=String(m.fileid);e.innerHTML=`<div class="thumb-wrap"><div class="check">✓</div><img data-thumb-fileid="${m.fileid}" alt="${esc(m.name)}" loading="lazy">${(m.contenttype||"").startsWith("video/")?'<div class="video-badge">▶ vidéo</div>':""}</div><div class="tile-info" title="${esc(m.name)}">${esc(m.name)}</div>`;e.querySelector(".check").onclick=ev=>{ev.stopPropagation();select(m,e)};e.querySelector(".thumb-wrap").onclick=()=>viewer(m);g.appendChild(e)}thumbs(ms,g);syncSel()}
async function thumbs(items,root=document,size="400x400"){const ids=items.map(x=>x.fileid).filter(Boolean);for(let i=0;i<ids.length;i+=80){try{const d=await api("getthumbslinks",{fileids:ids.slice(i,i+80).join(","),size,crop:1});for(const t of d.thumbs||[]){if(Number(t.result)!==0||!t.hosts?.length||!t.path)continue;const img=root.querySelector(`img[data-thumb-fileid="${String(t.fileid)}"]`);if(img)img.src=`https://${t.hosts[0]}${t.path}`}}catch(e){console.warn(e)}}}
function select(m,e){const id=String(m.fileid);if(S.selected.has(id)){S.selected.delete(id);e.classList.remove("selected")}else{S.selected.set(id,m);e.classList.add("selected")}syncSel()}
function syncSel(){const n=S.selected.size;$("#selectionCount").textContent=n;$("#selectionBar").classList.toggle("hidden",n===0);$$('.tile[data-fileid]').forEach(e=>e.classList.toggle("selected",S.selected.has(e.dataset.fileid)))}
function clearSel(){S.selected.clear();syncSel()}
async function createAlbum(name){const ids=[...S.selected.values()].map(x=>x.fileid);if(!ids.length)throw new Error("Aucune sélection");const d=await api("collection_create",{name,type:0,fileids:ids.join(",")});return Array.isArray(d.collection)?d.collection[0]:d.collection}
async function addAlbum(id){const ids=[...S.selected.values()].map(x=>x.fileid);if(!ids.length)throw new Error("Aucune sélection");return api("collection_linkfiles",{collectionid:id,fileids:ids.join(",")})}
async function albums(){busy(true);try{const d=await api("collection_list",{showfiles:1,pagesize:4});S.albums=(d.collections||[]).filter(a=>!a.system);renderAlbums()}catch(e){toast(`Albums : ${e.message}`,5000)}finally{busy(false)}}
function renderAlbums(){const g=$("#albumGrid");g.innerHTML="";$("#albumsEmpty").classList.toggle("hidden",S.albums.length>0);for(const a of S.albums){const e=document.createElement("div");e.className="album-card";e.innerHTML=`<div class="album-title">${esc(a.name)}</div><div class="album-count">${Number(a.items||0)} élément(s)</div><button class="secondary wide">Ouvrir</button>`;e.querySelector("button").onclick=()=>openAlbum(a.id);g.appendChild(e)}}
async function openAlbum(id){busy(true);try{const d=await api("collection_details",{collectionid:id});S.album=d.collection;$("#albumViewTitle").textContent=S.album.name||"Album";$("#albumViewMeta").textContent=`${S.album.items||0} élément(s)`;const g=$("#albumViewGrid");g.innerHTML="";const items=(S.album.contents||[]).filter(media);for(const m of items){const e=document.createElement("div");e.className="tile";e.innerHTML=`<div class="thumb-wrap"><img data-thumb-fileid="${m.fileid}" alt="${esc(m.name)}" loading="lazy">${(m.contenttype||"").startsWith("video/")?'<div class="video-badge">▶ vidéo</div>':""}</div><div class="tile-info">${esc(m.name)}</div>`;e.querySelector(".thumb-wrap").onclick=()=>viewer(m);g.appendChild(e)}$("#albumViewDialog").showModal();await thumbs(items,g)}catch(e){toast(`Album : ${e.message}`,5000)}finally{busy(false)}}
async function viewer(m){const d=$("#viewerDialog");$("#viewerCaption").textContent=m.name||"";const img=$("#viewerImage");img.removeAttribute("src");d.showModal();try{const x=await api("getthumbslinks",{fileids:m.fileid,size:"2048x1024",crop:0});const t=x.thumbs?.[0];if(!t||Number(t.result)!==0||!t.hosts?.length)throw new Error(t?.error||"Aperçu indisponible");img.src=`https://${t.hosts[0]}${t.path}`}catch(e){$("#viewerCaption").textContent=`${m.name||""} — ${e.message}`}}
async function share(pwd){if(!S.album?.id)throw new Error("Aucun album ouvert");const p=await api("getcollectionpublink",{collectionid:S.album.id});if(!p.linkid||!p.link)throw new Error("Lien non créé");if(pwd){try{await api("changepublink",{linkid:p.linkid,linkpassword:pwd})}catch(e){try{await api("deletepublink",{linkid:p.linkid})}catch{}throw new Error("Mot de passe non appliqué : lien supprimé par sécurité")}}return p.link}
function view(v){$$('.tab').forEach(t=>t.classList.toggle("active",t.dataset.view===v));$("#viewPhotos").classList.toggle("hidden",v!=="photos");$("#viewAlbums").classList.toggle("hidden",v!=="albums");if(v==="albums")albums()}
async function boot(){consume();$("#clientIdInput").value=S.client;$("#basePathInput").value=S.base;$("#btnSaveAndLogin").onclick=oauth;$("#btnLogout").onclick=logout;$("#btnSettings").onclick=()=>{screen("setup");$("#clientIdInput").value=S.client;$("#basePathInput").value=S.base};$("#btnRefresh").onclick=()=>folder(S.path||S.base,false);$("#btnUp").onclick=()=>{const p=S.stack.pop();if(p)folder(p,false);else if(S.path!==S.base)folder(S.base,false)};$("#btnClearSelection").onclick=clearSel;$$('.tab').forEach(t=>t.onclick=()=>view(t.dataset.view));$("#btnRefreshAlbums").onclick=albums;$("#btnCreateAlbum").onclick=()=>{$("#albumNameInput").value="";$("#albumDialog").showModal()};$("#btnConfirmCreateAlbum").onclick=async ev=>{ev.preventDefault();const n=$("#albumNameInput").value.trim();if(!n)return toast("Donne un nom à l'album.");busy(true);try{await createAlbum(n);$("#albumDialog").close();clearSel();toast(`Album « ${n} » créé.`)}catch(e){toast(e.message,5000)}finally{busy(false)}};$("#btnAddExisting").onclick=async()=>{await albums();const s=$("#albumSelect");s.innerHTML="";for(const a of S.albums){const o=document.createElement("option");o.value=a.id;o.textContent=`${a.name} (${a.items||0})`;s.appendChild(o)}if(!S.albums.length)return toast("Crée d'abord un album.");$("#addDialog").showModal()};$("#btnConfirmAdd").onclick=async ev=>{ev.preventDefault();const id=$("#albumSelect").value;if(!id)return;busy(true);try{await addAlbum(id);$("#addDialog").close();clearSel();toast("Ajouté à l'album.")}catch(e){toast(e.message,5000)}finally{busy(false)}};$("#btnCloseAlbumView").onclick=()=>$("#albumViewDialog").close();$("#viewerClose").onclick=()=>$("#viewerDialog").close();$("#btnShareAlbum").onclick=()=>{$("#sharePasswordInput").value="";$("#shareResult").classList.add("hidden");$("#shareDialog").showModal()};$("#btnConfirmShare").onclick=async ev=>{ev.preventDefault();busy(true);try{const l=await share($("#sharePasswordInput").value.trim());$("#shareLinkOutput").value=l;$("#shareResult").classList.remove("hidden");toast("Lien pCloud créé.")}catch(e){toast(e.message,6000)}finally{busy(false)}};$("#btnCopyShare").onclick=async()=>{const v=$("#shareLinkOutput").value;try{await navigator.clipboard.writeText(v)}catch{$("#shareLinkOutput").select();document.execCommand("copy")}toast("Lien copié.")};if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(console.warn);if(await valid()){screen("main");folder(S.base,false)}else{if(S.token)logout();screen("setup")}}
boot().catch(e=>toast(`Démarrage : ${e.message}`,6000));
})();