(()=>{
"use strict";
const $=s=>document.querySelector(s);
const SHARE_KEY="tri.demoShareLinks.v1";
const enc=o=>btoa(unescape(encodeURIComponent(JSON.stringify(o)))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
const dec=s=>JSON.parse(decodeURIComponent(escape(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((s.length+3)%4)))));
const hex=b=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("");
const hash=async s=>hex(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)));
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const svgThumb=(label,hue=180)=>`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="800"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="hsl(${hue} 70% 70%)"/><stop offset="1" stop-color="hsl(${(hue+45)%360} 60% 35%)"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/><circle cx="650" cy="150" r="70" fill="rgba(255,255,255,.8)"/><path d="M0 620L210 390l130 150 120-120 340 300H0z" fill="rgba(255,255,255,.72)"/><rect x="35" y="35" rx="18" width="390" height="70" fill="rgba(0,0,0,.35)"/><text x="60" y="83" font-family="Arial" font-size="34" fill="white">${label}</text></svg>`)}`;
const DEMO={d1:["20260714_091245.jpg","Petit-déjeuner",28,"image/jpeg"],d2:["20260714_101522.jpg","Plage",192,"image/jpeg"],d3:["20260714_103104.jpg","Baignade",207,"image/jpeg"],d4:["20260714_120015.jpg","Famille",330,"image/jpeg"],d5:["20260714_164530.jpg","Cocotiers",115,"image/jpeg"],d6:["20260714_180412.mp4","Vidéo plage",205,"video/mp4"],d7:["20260715_084402.jpg","Terrasse",32,"image/jpeg"],d8:["20260715_101159.jpg","Mer",195,"image/jpeg"],d9:["20260715_132010.jpg","Balade",100,"image/jpeg"],d10:["20260715_171804.jpg","Coucher soleil",18,"image/jpeg"],d11:["20260803_100022.jpg","Anniversaire",300,"image/jpeg"],d12:["20260803_110701.jpg","Gâteau",345,"image/jpeg"],d13:["20260803_120233.jpg","Famille",260,"image/jpeg"],d14:["20251225_090010.jpg","Noël",350,"image/jpeg"],d15:["20251225_120045.jpg","Repas",25,"image/jpeg"],d16:["20251225_160030.jpg","Famille",320,"image/jpeg"]};
function getShares(){try{return JSON.parse(localStorage.getItem(SHARE_KEY)||"{}")||{}}catch{return {}}}
function saveShare(name,link,days){const all=getShares();all[name]={link,created:Date.now(),days:Number(days||0)};localStorage.setItem(SHARE_KEY,JSON.stringify(all));renderSavedShare()}
function currentAlbumName(){return $("#albumViewTitle")?.textContent?.trim()||""}
function renderSavedShare(){const panel=$("#savedSharePanel"),input=$("#savedShareLink"),meta=$("#savedShareMeta");if(!panel||!input||!meta)return;const name=currentAlbumName(),s=getShares()[name];if(!name||!s){panel.classList.add("hidden");input.value="";meta.textContent="";return}input.value=s.link;const when=new Date(s.created).toLocaleString("fr-FR");meta.textContent=s.days?`créé le ${when} • expire après ${s.days} jours`:`créé le ${when} • sans expiration`;panel.classList.remove("hidden")}
function injectStyle(){const st=document.createElement("style");st.textContent=`#demoPublic{position:fixed;inset:0;z-index:1000;background:#f4f6f8;color:#111827;overflow:auto;font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif}.dp-head{position:sticky;top:0;z-index:3;background:#111827;color:white;padding:14px 18px;display:flex;justify-content:space-between;align-items:center;box-shadow:0 2px 10px #0003}.dp-title{font-size:20px;font-weight:800}.dp-sub{font-size:12px;color:#cbd5e1;margin-top:3px}.dp-close{border:0;background:#ffffff18;color:white;border-radius:10px;padding:8px 12px;font-size:18px}.dp-body{max-width:1100px;margin:auto;padding:18px}.dp-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:10px}.dp-tile{background:white;border:1px solid #e5e7eb;border-radius:14px;overflow:hidden;box-shadow:0 2px 8px #0000000a}.dp-img{aspect-ratio:1/1;background:#e5e7eb;position:relative}.dp-img img{width:100%;height:100%;object-fit:cover;display:block}.dp-name{padding:8px;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dp-play{position:absolute;inset:0;display:grid;place-items:center;font-size:54px;color:white;text-shadow:0 2px 12px #000}.dp-lock{max-width:430px;margin:12vh auto;background:white;padding:24px;border-radius:18px;box-shadow:0 15px 50px #0002}.dp-lock input{width:100%;padding:12px;border:1px solid #d1d5db;border-radius:10px;margin:12px 0}.dp-lock button{width:100%;padding:12px;border:0;border-radius:10px;background:#0f766e;color:white;font-weight:700}.dp-error{color:#b91c1c;margin-top:8px}.dp-view{position:fixed;inset:0;z-index:1100;background:#050505ee;display:grid;place-items:center}.dp-view img{max-width:92vw;max-height:82vh;object-fit:contain}.dp-view-card{color:white;text-align:center}.dp-x,.dp-nav{position:absolute;border:0;background:#ffffff20;color:white;border-radius:50%;width:46px;height:46px;font-size:28px}.dp-x{right:18px;top:18px}.dp-nav{top:50%;transform:translateY(-50%)}.dp-prev{left:15px}.dp-next{right:15px}.dp-cap{position:absolute;bottom:18px;left:70px;right:70px;text-align:center;color:white;font-size:13px}@media(max-width:700px){.dp-body{padding:10px}.dp-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.dp-title{font-size:18px}}`;document.head.appendChild(st)}
function makePublic(payload){injectStyle();const root=document.createElement("div");root.id="demoPublic";document.body.appendChild(root);const expired=payload.exp&&Date.now()>payload.exp;root.innerHTML=`<div class="dp-head"><div><div class="dp-title">${esc(payload.name||"Album partagé")}</div><div class="dp-sub">Album de démonstration • Tri Photo Albums</div></div><button class="dp-close" title="Fermer">✕</button></div><div class="dp-body"></div>`;root.querySelector(".dp-close").onclick=()=>{location.href=location.pathname};const body=root.querySelector(".dp-body");if(expired){body.innerHTML=`<div class="dp-lock"><h2>Lien expiré</h2><p>Ce lien de démonstration a dépassé sa date d'expiration.</p></div>`;return}const show=()=>renderGallery(body,payload);if(payload.ph){body.innerHTML=`<div class="dp-lock"><h2>Album protégé</h2><p>Saisis le mot de passe choisi lors du partage.</p><input id="dpPwd" type="password" autocomplete="current-password" placeholder="Mot de passe"><button id="dpUnlock">Ouvrir l'album</button><div id="dpErr" class="dp-error"></div></div>`;body.querySelector("#dpUnlock").onclick=async()=>{const v=body.querySelector("#dpPwd").value;if(await hash(v)===payload.ph)show();else body.querySelector("#dpErr").textContent="Mot de passe incorrect."}}else show()}
function renderGallery(body,p){const items=(p.ids||[]).map(id=>({id,data:DEMO[id]})).filter(x=>x.data);body.innerHTML=`<p><strong>${items.length}</strong> élément(s) partagés.</p><div class="dp-grid"></div>`;const g=body.querySelector(".dp-grid");items.forEach((x,i)=>{const [name,label,hue,type]=x.data;const e=document.createElement("div");e.className="dp-tile";e.innerHTML=`<div class="dp-img"><img src="${svgThumb(label,hue)}" alt="${esc(name)}">${type.startsWith("video/")?'<div class="dp-play">▶</div>':""}</div><div class="dp-name">${esc(name)}</div>`;e.querySelector(".dp-img").onclick=()=>openViewer(items,i);g.appendChild(e)})}
function openViewer(items,index){let i=index;const v=document.createElement("div");v.className="dp-view";document.body.appendChild(v);const draw=()=>{const [name,label,hue,type]=items[i].data;v.innerHTML=`<button class="dp-x">✕</button><button class="dp-nav dp-prev">‹</button>${type.startsWith("video/")?`<div class="dp-view-card"><div style="font-size:80px">▶</div><h2>${esc(name)}</h2><p>Lecture vidéo simulée en mode démonstration</p></div>`:`<img src="${svgThumb(label,hue)}" alt="${esc(name)}">`}<button class="dp-nav dp-next">›</button><div class="dp-cap">${esc(name)} • ${i+1}/${items.length}</div>`;v.querySelector(".dp-x").onclick=()=>v.remove();v.querySelector(".dp-prev").onclick=()=>{i=(i-1+items.length)%items.length;draw()};v.querySelector(".dp-next").onclick=()=>{i=(i+1)%items.length;draw()}};draw()}
async function buildShareLink(){const badge=$("#modeBadge");if(!badge||badge.classList.contains("hidden"))return null;const name=currentAlbumName()||"Album partagé";const ids=Array.from(document.querySelectorAll("#albumViewGrid img[data-thumb-fileid]")).map(x=>x.dataset.thumbFileid);const pwd=$("#sharePasswordInput")?.value||"";const days=Number($("#shareExpiry")?.value||0);const payload={v:1,name,ids,ph:pwd?await hash(pwd):"",exp:days?Date.now()+days*86400000:0};return {link:`${location.origin}${location.pathname}?demo-public=${enc(payload)}`,days}}
async function copyText(v){try{await navigator.clipboard.writeText(v)}catch{const i=$("#savedShareLink");if(i){i.select();document.execCommand("copy")}}}
function wire(){const confirm=$("#btnConfirmShare");if(confirm){confirm.addEventListener("click",async e=>{const badge=$("#modeBadge");if(!badge||badge.classList.contains("hidden"))return;e.preventDefault();e.stopImmediatePropagation();const res=await buildShareLink();if(!res)return;$("#shareLinkOutput").value=res.link;$("#shareResult").classList.remove("hidden");saveShare(currentAlbumName(),res.link,res.days);const t=$("#toast");if(t){t.textContent="Lien de démonstration créé et mémorisé.";t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),2500)}},true)}
 const dlg=$("#albumViewDialog");if(dlg){new MutationObserver(renderSavedShare).observe($("#albumViewTitle"),{childList:true,subtree:true,characterData:true});dlg.addEventListener("toggle",renderSavedShare);dlg.addEventListener("close",renderSavedShare)}
 $("#btnSavedCopy")?.addEventListener("click",async()=>{const v=$("#savedShareLink")?.value||"";if(v){await copyText(v);const t=$("#toast");if(t){t.textContent="Lien copié.";t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),2000)}}});
 $("#btnSavedOpen")?.addEventListener("click",()=>{const v=$("#savedShareLink")?.value||"";if(v)window.open(v,"_blank","noopener")});
 renderSavedShare()}
const params=new URLSearchParams(location.search);const packed=params.get("demo-public");if(packed){try{makePublic(dec(packed))}catch(e){console.error(e);injectStyle();const r=document.createElement("div");r.id="demoPublic";r.innerHTML='<div class="dp-lock"><h2>Lien invalide</h2><p>Impossible de lire cet album de démonstration.</p></div>';document.body.appendChild(r)}}else{wire()}
})();